version: '3.9'
services:
  app-server:
    image: localhost:5000/backend
    deploy:
      replicas: 2
    ports:
      - 3000:3000
    networks:
      - backend-network
    depends_on:
      - mongo
  web-server:
    image: localhost:5000/frontend
    deploy:
      replicas: 2
    ports:
      - 80:80
    networks:
      - backend-network
    depends_on:
      - app-server
  mongo:
    image: mongo
    deploy:
      replicas: 1
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - backend-network      
    volumes:
      - app-volume:/data/db
  mongo-express:
    image: mongo-express
    deploy:
      replicas: 1
    restart: always
    ports:
      - 8081:8081
    networks:
      - backend-network
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongo
volumes:
  app-volume:
    driver: local
networks:
  frontend-network:
    driver: overlay
  backend-network:
    driver: overlay

